### ISSUE TITLE
Problema com o Zeos

### ISSUE THREAD

**Issue by laffsj** [frones/ZeosLib#2]
Gabriel queria ver se pode me dar uma ajuda.
Eu estava usando a versão 6248, atualizei para a mais recente, após fazer isso, algumas telas começaram a dar erros, alguns campos aparecem com valores de outros campos. Eu consegui resolver isso entrando no zquery, removendo os campos e adicionando de novo, fazendo isso volta a funcionar tudo. Tem algo que posso fazer para não ter que passar por todas as telas e ter que fazer isso de remover os campos e adicionar novamente?
Obrigado pela atenção.

**Comment by frones** [comment]
Colega, eu não sei exatamente o que mudou, então é difícil dar uma resposta certeira. Mas o que eu faria é o seguinte:

1. Pegue um caso que os campos estão desatualizados e com problema e veja como os campos estão declarados no DFM (veja principalmente o atributo Size, que eu desconfio ser o problema).
2. Remova os campos e readicione via IDE.
3. Olhe novamente como ficaram os campos, para identificar o que muda.
4. Aplique essa mesma mudança em todos os seus DFMs com um regex/script/programa.

Acho que essa deve ser a melhor maneira de resolver esse problema. Uma observação que eu faço é que eu nunca adiciono campos nos datasets em tempo de design a menos que eu realmente precise deles. Eu deixo que o dataset adicione dinamicamente no momento da abertura. Assim não preciso me preocupar muito quando mudo campos no BD.

**Comment by ecostas** [comment]
Estou tendo exatamente esse problema. Cheguei a criar um projeto somente com um TZConnection, um TZTable, TDataset e TDBGrid e tive o problema já dentro do IDE. Campos inteiros estão aparecendo zerados e o CNPack os está identificando como TWordField, mas não todos. Não carreguei a definição dos campos via Field Editor. O problema acontece tanto com o MySQL quanto com o MariaDB, embora o phpMyAdmin apresente os valores corretamente.

Os problemas aparentemente começaram depois de atualização do Zeoslib feita nas últimas semanas. Tentarei arrumar uma versão antiga e mais confiável. 

A propósito, resolvi testar os exemplos para ver se funcionavam ou achar a diferença em relação ao meu programa. O script de geração para o MySQL não funciona, tampouco o projeto ZSimpleMain.

**Comment by ecostas** [comment]
Estou tendo exatamente esse problema. Cheguei a criar um projeto somente com um TZConnection, um TZTable, TDataset e TDBGrid e tive o problema já dentro do IDE. Campos inteiros estão aparecendo zerados e o CNPack os está identificando como TWordField, mas não todos. Não carreguei a definição dos campos via Field Editor. O problema acontece tanto com o MySQL quanto com o MariaDB, embora o phpMyAdmin apresente os valores corretamente.

Os problemas aparentemente começaram depois de atualização do Zeoslib feita nas últimas semanas. Tentarei arrumar uma versão antiga e mais confiável. 

A propósito, resolvi testar os exemplos para ver se funcionavam ou achar a diferença em relação ao meu programa. O script de geração para o MySQL não funciona, tampouco o projeto ZSimpleMain.

Deixei para testar mais depois de dormir. A versão 7.2.6 parece estar normal. Farei mais alguns testes, mas não estava tendo problemas com ela antes.
