### ISSUE TITLE
Problem connecting to database using Firebird 4.0.0 on Android

### ISSUE THREAD

**Issue by cayque10** [frones/ZeosLib#3]
Hi. I'm testing the "Android and Firebird embedded" example and I'm getting some errors.

To get started, I'm using the Firebird-4.0.0.2496 ARM64 library for Android [https://firebirdsql.org/en/firebird-4-0/](url)

Well, based on that I identified that libicui18n.so.63, icudt63l.dat, libicudata.so.63 and libicuuc.so.63 files are not present in the Firebird for Android fileset. Based on that, I commented on the three lines that refer to these files.

As an already existing database, I tried to connect, but the following error occurred:

```
"First chance exception at $000000709A339F98. Exception class EZIBSQLException with message
'SQL Error: Unsuccessful execution caused by a system error that precludes successful execution of subsequent statements
Code: -902 Message: Connect to "/data/user/0/com.embarcadero.Project1/files/DBTESTE.FDB" as user "SYSDBA"; GDS Code: 335545167'.
Process Project1.apk (23108)"
```

According to the link: [https://github.com/cincuranet/FirebirdSql.Data.FirebirdClient/blob/master/Provider/src/FirebirdSql.Data.FirebirdClient/Common/IscErrorMessages.cs](url) code 335545167 references the following: "Could not find acceptable ICU library".

I'm compiling using Android 64 Bit, Delphi 10.4, Xiaomi Mi 8 lite.

Is there any way to solve this? Thanks.

**Comment by frones** [comment]
Hi, @cayque10 !
I'm only hosting a mirror here and it's been quite some time since I last tried anything new with Zeos. Please connect with the [official help forums](https://zeoslib.sourceforge.io/) for assistance as I don't think any of the devs follow this mirror.
