### ISSUE TITLE
Error connecting to sqlite

### ISSUE THREAD

**Issue by cayque10** [frones/ZeosLib#4]
Hello. This time I'm running the connection tests on Sqlite for Android. When trying to connect I get the following error: "System Error. Code: 20. Nota directory."

What am I wrong?

Thanks for the help.

Test Code:

` ZConnection1.LibraryLocation := TPath.Combine(TPath.GetDocumentsPath, 'libsqlite.so');
  ZConnection1.Database := TPath.Combine(TPath.GetDocumentsPath, 'db_sqlite.db');
  ZConnection1.Protocol := 'sqlite';
  ZConnection1.ClientCodepage := 'UTF-8';
  ZConnection1.Connected := true;`

**Comment by frones** [comment]
Hi, @cayque10 !
I'm only hosting a mirror here and it's been quite some time since I last tried anything new with Zeos. Please connect with the [official help forums](https://zeoslib.sourceforge.io/) for assistance as I don't think any of the devs follow this mirror.
